#**Module - 01. pytorch fundamental**

---


1.   List item
2.   List item



- resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:
print('hello pytorch!')

hello pytorch!


In [2]:
!nvidia-smi # knowing about gpu which i am currently using

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## introduction to tensor

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
type(scalar)

torch.Tensor

In [6]:
# dimention of tensor "ndim" attribute
scalar.ndim

0

In [7]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [8]:
# vecto
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [9]:
type(vector)

torch.Tensor

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# matrix
matrix = torch.tensor([
    [7,9],
    [9,10],
    [11,29]
])
matrix

tensor([[ 7,  9],
        [ 9, 10],
        [11, 29]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([3, 2])

In [15]:
matrix[0]

tensor([7, 9])

In [16]:
# tensor
tensor1 = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9],
]])
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
tensor1.ndim

3

In [18]:
tensor1.shape

torch.Size([1, 3, 3])

In [19]:
# creating random tensor of size(3,4) using torch.rand()
r_tensor = torch.rand(size=(3,4))
r_tensor, r_tensor.ndim, r_tensor.dtype

(tensor([[0.0567, 0.3458, 0.2677, 0.9324],
         [0.0809, 0.7135, 0.6863, 0.6016],
         [0.2119, 0.7965, 0.7051, 0.7789]]),
 2,
 torch.float32)

In [20]:
# creating random tensor of size (120,240,3)
image = torch.rand(size=(120,240,3))
image.shape, image.ndim

(torch.Size([120, 240, 3]), 3)

In [21]:
# create a tensor of all zero
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [22]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [23]:
# creating a range of values like 0 to 10
# torch.arange(start, end, step)
zero_to_ten = torch.arange(start=0,end=11,step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# can create a tensor of zeros similar to another tensor
ten_zero = torch.zeros_like(input=zero_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [25]:
# float 32 tensor (defaul)
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [26]:
# float 16 tensor
float_16_tensor = torch.tensor([3,5,7],dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 5., 7.], dtype=torch.float16), torch.float16)

##Manipulating Tensor (tensor operation)

In [27]:
# create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
# multiplication using build in function
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [30]:
torch.mul(tensor,12)

tensor([12, 24, 36])

In [31]:
# substract 10
tensor - 10

tensor([-9, -8, -7])

## matrix multiplication
- elementwise multiplication(Hadamard Product)
- matrix multiplication(classical)


In [32]:
# element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [34]:
A = torch.randn(2, 3)
B = torch.randn(3, 4)
torch.matmul(A, B)

tensor([[-1.2134, -0.0696, -0.2895,  0.4275],
        [-1.0509,  0.6482, -0.3473, -2.1030]])

In [35]:
a = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
# teanspose of matix a
a.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

##Finding the min, max, mean, sum, etc (aggregation)

In [37]:
# create a tensor using arange
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# finding min
x.min()

tensor(0)

In [39]:
# finding max
x.max()

tensor(90)

In [40]:
# finding average - need folat or complex datatype
x = x.type(torch.float32)
x.mean()

tensor(45.)

In [41]:
# find the sum
x.sum()

tensor(450.)

##Finding the positional min and max

In [42]:
x = torch.arange(11,99,3)
x

tensor([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62,
        65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [43]:
# find the index of minimum value with argmin()
x.argmin()

tensor(0)

In [44]:
# finding the index of maximum value with argmax()
x.argmax()


tensor(29)

##Rehaping, stacking, squeezing, unsqueezing tensor

In [45]:
x = torch.arange(1.,10.)
x,x.shape,x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [46]:
# tensor.reshape(input the shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [47]:
# tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
# changing view tenssor data change original tensor
x_view = x.view(3,3)
x_view,x_view.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [48]:
# torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##Indexing (selecting data from tensors)

In [49]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
# indexing bracket by bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [53]:
x[0][1]

tensor([4, 5, 6])

In [55]:
x[0][2][2]

tensor(9)

In [57]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [58]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [59]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [60]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])