## Module - 01. pytorch fundamental
- resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/


In [2]:
print('hello pytorch!')

hello pytorch!


In [3]:
!nvidia-smi # knowing about gpu which i am currently using

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


## introduction to tensor

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
type(scalar)

torch.Tensor

In [7]:
# dimention of tensor "ndim" attribute
scalar.ndim

0

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [9]:
# vecto
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [10]:
type(vector)

torch.Tensor

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# matrix
matrix = torch.tensor([
    [7,9],
    [9,10],
    [11,29]
])
matrix

tensor([[ 7,  9],
        [ 9, 10],
        [11, 29]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([3, 2])

In [16]:
matrix[0]

tensor([7, 9])

In [17]:
# tensor
tensor1 = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9],
]])
tensor1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
tensor1.ndim

3

In [19]:
tensor1.shape

torch.Size([1, 3, 3])

In [20]:
# creating random tensor of size(3,4) using torch.rand()
r_tensor = torch.rand(size=(3,4))
r_tensor, r_tensor.ndim, r_tensor.dtype

(tensor([[0.8927, 0.4737, 0.5071, 0.7541],
         [0.9260, 0.9300, 0.5390, 0.6779],
         [0.2560, 0.8314, 0.5274, 0.1070]]),
 2,
 torch.float32)

In [21]:
# creating random tensor of size (120,240,3)
image = torch.rand(size=(120,240,3))
image.shape, image.ndim

(torch.Size([120, 240, 3]), 3)

In [22]:
# create a tensor of all zero
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [25]:
# creating a range of values like 0 to 10
# torch.arange(start, end, step)
zero_to_ten = torch.arange(start=0,end=11,step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# can create a tensor of zeros similar to another tensor
ten_zero = torch.zeros_like(input=zero_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [28]:
# float 32 tensor (defaul)
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [29]:
# float 16 tensor
float_16_tensor = torch.tensor([3,5,7],dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 5., 7.], dtype=torch.float16), torch.float16)