In [60]:
import torch
print(torch.__version__)

2.9.0+cu126


In [61]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU:Tesla T4


## Creating Tensor

In [62]:
# using empty
a=torch.empty(2,3)

In [63]:
# check type
type(a)

torch.Tensor

In [64]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [65]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [66]:
# using rand
torch.rand(2,3) # values between 0 and 1

tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [67]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [68]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [69]:
# using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [70]:
# using eye for identity matrix
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Tenor Shapes

In [71]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
x.shape

torch.Size([2, 3])

In [73]:
torch.empty_like(x)

tensor([[    139203119668608,           703365008, 4575657221408423936],
        [                  0,                   0,          1065353216]])

In [74]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

## Tensor data type

In [75]:
x.dtype # finding data type

torch.int64

In [76]:
# assigning data type during creation
torch.tensor([1.0,20.0,3.0],dtype=torch.int32)

tensor([ 1, 20,  3], dtype=torch.int32)

In [77]:
# changing date type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operation

In [78]:
x = torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [79]:
# addition
x +2

tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])

In [80]:
# substractin
x-2

tensor([[-1.7373, -1.9572],
        [-1.7920, -1.8820]])

In [81]:
# multiplicatin
x*2

tensor([[0.5254, 0.0857],
        [0.4161, 0.2361]])

In [82]:
# divition
x/2

tensor([[0.1313, 0.0214],
        [0.1040, 0.0590]])

In [83]:
# integet division
x//2

tensor([[0., 0.],
        [0., 0.]])

In [84]:
# mod
x%2

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [85]:
# power
x**3

tensor([[1.8127e-02, 7.8621e-05],
        [9.0026e-03, 1.6446e-03]])

## Element wise opeation

In [86]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [87]:
# addition
a+b

tensor([[1.1186, 1.4921, 0.9357],
        [1.0899, 0.5967, 1.7253]])

In [88]:
# multiplicatin
a*b

tensor([[0.1213, 0.5565, 0.1594],
        [0.2381, 0.0746, 0.7426]])

In [89]:
# division
a/b

tensor([[0.1221, 0.9724, 3.1790],
        [2.6049, 2.3445, 1.0942]])

In [90]:
#poewr
a ** b

tensor([[0.1225, 0.7927, 0.9267],
        [0.9303, 0.8560, 0.9180]])

In [91]:
# mod
a%b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [92]:
c = torch.tensor([1,-2,3,-4])

In [93]:
# abs
c.abs()

tensor([1, 2, 3, 4])

In [94]:
# neative - reverse the symbol
c.neg()

tensor([-1,  2, -3,  4])

In [95]:
d = torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [96]:
# round
d.round()

tensor([2., 2., 4., 4.])

In [97]:
# ceil
d.ceil()

tensor([2., 3., 4., 5.])

In [98]:
# floor
d.floor()

tensor([1., 2., 3., 4.])

In [99]:
# clamp
d.clamp(min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction operation

In [100]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [101]:
# sum
torch.sum(e)

tensor(29.)

In [102]:
# sum along columns
torch.sum(e,dim=0)

tensor([ 5., 15.,  9.])

In [103]:
# sum along row
torch.sum(e, dim=1)

tensor([10., 19.])

In [104]:
# mean
e.mean()

tensor(4.8333)

In [105]:
# mean column wise
e.mean(dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [106]:
# mean row wise
e.mean(dim=1)

tensor([3.3333, 6.3333])

In [107]:
# median
e.median()

tensor(4.)

In [108]:
# max and min
e.max(), e.min()

(tensor(9.), tensor(0.))

In [109]:
# product
e.prod()

tensor(0.)

In [110]:
# standard deviation
e.std()

tensor(3.8687)

In [111]:
# variance
e.var()

tensor(14.9667)

In [112]:
# argmax - give max element position
e.argmax()

tensor(4)

## Matrix operation

In [113]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
f,g

(tensor([[8, 0, 7],
         [0, 0, 9]]),
 tensor([[5, 7],
         [3, 9],
         [4, 0]]))

In [114]:
# matrix multipilcaton
f.matmul(g)

tensor([[68, 56],
        [36,  0]])

In [117]:
# dot product of vector
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
vector1.dot(vector2)

tensor(11)

In [126]:
# treanspos
f,f.transpose(0,1)

(tensor([[8, 0, 7],
         [0, 0, 9]]),
 tensor([[8, 0],
         [0, 0],
         [7, 9]]))

In [129]:
# determinant
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h.det()

tensor(-275.)

In [130]:
# inverse
h.inverse()

tensor([[ 0.1382, -0.1855,  0.0182],
        [-0.1564,  0.1309,  0.1636],
        [ 0.0945,  0.0836, -0.1455]])

## Comparison operation

In [131]:
i = torch.randint(size=(2,3),low = 0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)
i,j

(tensor([[6, 1, 5],
         [5, 0, 4]]),
 tensor([[3, 8, 8],
         [3, 3, 5]]))

In [132]:
# grater than
i>j

tensor([[ True, False, False],
        [ True, False, False]])

In [133]:
#equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [134]:
#log
i.log10()

tensor([[0.7782, 0.0000, 0.6990],
        [0.6990,   -inf, 0.6021]])

In [135]:
# exp
i.exp()

tensor([[403.4288,   2.7183, 148.4132],
        [148.4132,   1.0000,  54.5981]])

In [136]:
#sogmoid
# The sigmoid (a.k.a. logistic) function is a smooth, S-shaped function that maps any real number to a value between 0 and 1.
i.sigmoid()

tensor([[0.9975, 0.7311, 0.9933],
        [0.9933, 0.5000, 0.9820]])